version: '3'
services:
    nginx:
        container_name: nginx
        restart: always
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./www:/var/www/html
            - ./logs:/var/log/nginx
            - ./sites:/etc/nginx/conf.d
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
            - "443:443"
